export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import QueryProvider from "@/providers/QueryProvider";
import "./globals.css";
import Aside from "@/components/aside/Aside";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <div className="flex h-screen w-full bg-gray-50">
            <Aside />
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
